apiVersion: apps/v1
kind: Deployment
metadata:
  name:  usermgmtback
  namespace: userapp
  labels:
    app:  usermgmtback
spec:
  selector:
    matchLabels:
      app: usermgmtback
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  usermgmtback
    spec:
      containers:
      - name:  usermgmtback
        image:  kk2104/usermgmtback:v4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  9000
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: usermgmtback
  namespace: userapp
spec:
  selector:
    app: usermgmtback
  type: ClusterIP
  ports:
  - name: usermgmtback
    protocol: TCP
    port: 9000
    targetPort: 9000
